name: Eve-O Preview Release - lutris script

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        echo "EVE_O_PREVIEW=https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/Release-${{github.event.release.tag_name}}-Linux.zip" >> $GITHUB_ENV

    - uses: microsoft/variable-substitution@v1 
      with:
        files: './src/eve-o-preview.yaml'
    
    - uses: actions/upload-release-asset@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./src/eve-o-preview.yaml"
          asset_name: "eve-o-preview.yaml"
          asset_content_type: application/yaml
