name: Eve-O Preview Release - PDF generator

on:
  release:
    types: [published]

jobs:
  make-pdf:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
   
    - name: Generate PDF Document
      uses: cornelius/action-md-as-pdf@main
      with:
        markdown_file: README.md
        css_file: pdf/readme.css
        pdf_file: README.pdf

    - name: Publish PDF Document
      uses: actions/upload-release-asset@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "README.pdf"
          asset_name: "Eve-O-Preview.pdf"
          asset_content_type: application/pdf
